### ISSUE TITLE
从痛点，爽点，痒点看区块链 · 沉风网事

### ISSUE THREAD

**Issue by myself659** [myself659/myself659.github.io#1]
https://blog.ipds.top/2018/03/04/%E4%BB%8E%E7%97%9B%E7%82%B9%E7%88%BD%E7%82%B9%E7%97%92%E7%82%B9%E7%9C%8B%E5%8C%BA%E5%9D%97%E9%93%BE/

**Comment by myself659** [comment]
第一条评论 测试一下

**Comment by myself659** [comment]
欢迎交流与沟通

**Comment by lejoys** [comment]
facebook libra争议不断 前路艰辛
